### ISSUE TITLE
Nggak akurat

### ISSUE THREAD

**Issue by lawbyte** [widhisec/clonehub#1]
Pilihnya nomor 5 tapi clone nya nomor 7
Terus di coba lagi pilih 5 tetep clone nya ke nomor 7
Coba ganti user juga sama pas pilih nomor 3 eh loncat ke nomor 10+ kek random gitu

**Comment by widhisec** [comment]
> Pilihnya nomor 5 tapi clone nya nomor 7 Terus di coba lagi pilih 5 tetep clone nya ke nomor 7 Coba ganti user juga sama pas pilih nomor 3 eh loncat ke nomor 10+ kek random gitu

sekarang udah saya perbaiki terimakasih.
